src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category_name = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Figurines::class)]
    private Collection $figurines;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    public function __construct()
    {
        $this->figurines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Figurines>
     */
    public function getFigurines(): Collection
    {
        return $this->figurines;
    }

    public function addFigurine(Figurines $figurine): self
    {
        if (!$this->figurines->contains($figurine)) {
            $this->figurines->add($figurine);
            $figurine->setCategory($this);
        }

        return $this;
    }

    public function removeFigurine(Figurines $figurine): self
    {
        if ($this->figurines->removeElement($figurine)) {
            // set the owning side to null (unless already changed)
            if ($figurine->getCategory() === $this) {
                $figurine->setCategory(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Figurines.php
<?php

namespace App\Entity;

use App\Repository\FigurinesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FigurinesRepository::class)]
class Figurines
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\ManyToOne(inversedBy: 'figurines')]
    private ?Category $category;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $shortDescription = null;

    #[ORM\OneToMany(mappedBy: 'figurine', targetEntity: PurchaseItem::class)]
    private Collection $purchaseItems;

    

    public function __construct()
    {
        $this->purchaseItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    /**
     * @return Collection<int, PurchaseItem>
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems->add($purchaseItem);
            $purchaseItem->setFigurine($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getFigurine() === $this) {
                $purchaseItem->setFigurine(null);
            }
        }

        return $this;
    }

    
}

src/Form/FigurineType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Figurines;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class FigurineType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la figurine',
                'attr' => [
                    'placeholder' => 'Entrez le nom de la figurine'
                ]
            ])
            ->add('picture', UrlType::class, [
                'label' => 'Image de la figurine',
                'attr' => ['placeholder' => 'Entrez une URL d\'image ']
            ])

            ->add('picture', FileType::class, [
                'label' => 'Image de la figurine',
                'attr' => ['placeholder' => 'Entrez une URL d\'image ']
            ])

            ->add('price', MoneyType::class, [
                'label' => 'Prix de la figurine',
            ])

            ->add('shortDescription', TextareaType::class, [
                'label' => 'Description de la figurine',
                'attr' => [
                    'placeholder' => 'décrivez la figurine'
                ]
            ])
            ->add('category', EntityType::class, [
                'label' => 'Catégorie',
                'placeholder' => '-- Choisissez une catégorie --',
                'class' => Category::class,
                'choice_label' => function (Category $category) {
                    return($category->getCategoryName());
                }
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Figurines::class,
        ]);
    }
}

src/Controller/FigurineController.php
<?php

namespace App\Controller;

use App\Entity\Figurines;
use App\Form\FigurineType;
use App\Repository\CategoryRepository;
use App\Repository\FigurinesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class FigurineController extends AbstractController
{
    #[Route('/{slug}', name: 'figurine_category', priority: -1)]
    public function category($slug, CategoryRepository $categoryRepository): Response
    {
        $category = $categoryRepository->findOneBy([
            'slug' => $slug
        ]);
                // si la catégorie n'existe pas
        if (!$category) {
             throw $this->createNotFoundException('La catégorie n\'existe pas !!!');
        }

        return $this->render('figurine/category.html.twig', [
            'slug' => $slug,
            'category' => $category
        ]);
    }


    #[Route('/admin/figurines', name: 'app_figurines', methods: ['GET'])]
    public function index(FigurinesRepository $figurinesRepository): Response
    {
        return $this->render('figurine/index.html.twig', [
            'figurines' => $figurinesRepository->findAll(),
        ]);
    }

    
    #[Route('/{category_slug}/{slug}', name:'figurine_show')] 
    public function show($slug, FigurinesRepository $figurinesRepository)
    {
        $figurine = $figurinesRepository->findOneBy(['slug' => $slug]);

        if (!$figurine) {
                throw new NotFoundHttpException("Le produit n'existe pas !!!");
        }

        return $this->render('figurine/show.html.twig', [
            'figurine' => $figurine,
        ]);
    }

    #[Route('figurine/show/{id}', name: 'fig_show', methods: ['GET'])]
    public function showFigurine(Figurines $figurine): Response
    {
        return $this->render('figurine/show.figurine.html.twig', [
            'figurine' => $figurine,
        ]);
    }


    #[Route('/admin/figurine/create', name:'figurine_create')]
    public function create(Request $request, SluggerInterface $slugger, EntityManagerInterface $em)
    {
        $figurine = new Figurines;

        $form = $this->createForm(FigurineType::class, $figurine);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
        
            $figurine->setSlug(strtolower($slugger->slug($figurine->getName())));

            $em->persist($figurine);
            $em->flush();

            return $this->redirectToRoute('app_admin', [
                'category_slug' => $figurine->getCategory()->getSlug(),
                'slug' => $figurine->getSlug()
            ]);
        }

        $formView = $form->createView();

        return $this->render('figurine/create.html.twig', [
            'formView' => $formView
        ]); 
    }

    #[Route('/admin/figurine/{id}/delete', name: 'figurines_delete', methods: ['POST'])]
    public function delete(Request $request, Figurines $figurine, FigurinesRepository $figurinesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$figurine->getId(), $request->request->get('_token'))) {
            $figurinesRepository->remove($figurine, true);
        }

        return $this->redirectToRoute('app_admin', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/admin/figurine/{id}/edit', name: 'figurines_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Figurines $figurine, FigurinesRepository $figurinesRepository): Response
    {
        $form = $this->createForm(FigurineType::class, $figurine);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $figurinesRepository->save($figurine, true);

            return $this->redirectToRoute('app_figurines', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('figurine/edit.html.twig', [
            'figurine' => $figurine,
            'form' => $form,
        ]);
    }
}

templates/figurine/_delete_form.html.twig
<form method="post" action="{{ path('figurines_delete', {'id': figurine.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ figurine.id) }}">
    <button class="btn">Delete</button>
</form>

templates/figurine/_figurine_card.html.twig
<div class="col-xl-3 col-lg-4 col-md-5 col-sm-7 mx-auto mt-5">
    <div class="card w-auto bg-primary">
        <img class="w-50 mt-2 m-auto" src="{{figurine.picture}}" alt="img">
        <div class="card-body mx-auto">
            <h4 class=>{{figurine.name}} ({{figurine.price / 100}}€)</h4>
            <span class="badge rounded-pill bg-info">
                {{figurine.category.categoryName}}
            </span>
            <p class="card-text">
            {{figurine.shortDescription}}
            </p>
            <a href="{{ path('figurine_show', {
                    'category_slug': figurine.category.slug, 
                    'slug': figurine.slug
                }) 
            }}" class="btn btn-info">Détail</a>
            <a href="{{ path('cart_add', {'id': figurine.id})}}" class="btn btn-success">Acheter</a>
        </div>
    </div>
</div>

templates/figurine/_form.html.twig
<?php
?>
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn" onclick="Confirmation">{{ button_label|default('Save') }}</button>
    
{{ form_end(form) }}

templates/figurine/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Catégorie : {{ slug }}
{% endblock %}

{% block body %}
    <ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{{path('homepage')}}">Accueil</a>
    </li>
    <li class="breadcrumb-item active">{{category.categoryName}}</li>
    </ol>
    

        <div class="container">
            <h1> Catégorie : {{category.categoryName}} </h1>
            <div class="row">
                {% for figurine in category.figurines %}
                
                    {% include "figurine/_figurine_card.html.twig" %}
               
                {% endfor %}
            </div>
        
        </div>

{% endblock %}

templates/figurine/create.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Ajout de figurine
{% endblock %}

{% block body %}
    <h1>Ajoutez une figurine :</h1>

    {{ form_start(formView)}}

    <div class="container">
        <div class="row">
            <div class="col">
            <form onsubmit=" voulez vous ajouter la fugurine ?">
                {{ form_row(formView.name) }}
                {{ form_row(formView.price) }}
                {{ form_row(formView.picture) }}
            </div>
            <div class="col">
                {{ form_row(formView.shortDescription) }}
                {{ form_row(formView.category) }}
            </div>
        </div>
    </div>

    {{ form_widget(formView)}}

    <button type="submit" class="btn btn-info" onclick="add()">
        <i class="fas fa-save" on></i>
        Ajouter
    </button>

    {{ form_end(formView)}}
</form>
{% endblock %}

templates/figurine/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Figurines{% endblock %}

{% block body %}
    <h1>Edit Figurines</h1>
    <div class="container">
        {{ include('figurine/_form.html.twig', {'button_label': 'Update'}) }}
        {{ include('figurine/_delete_form.html.twig') }}
        <a href="{{ path('app_figurines') }}">back to list</a>

        
    </div>
    
{% endblock %}

templates/figurine/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>
<div class="container"><table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for figurine in figurines %}
            <tr>
                <td>{{ figurine.id }}</td>
                <td>{{ figurine.name}}</td>
                <td>
                    <a href="{{ path('fig_show', {'id': figurine.id}) }}">show</a>
                    <a href="{{ path('figurines_edit', {'id': figurine.id}) }}">edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_users_new') }}">Create new</a> #}
    </div>
    
{% endblock %}

templates/figurine/show.figurine.html.twig
{% extends 'base.html.twig' %}

{% block title %}Figurines{% endblock %}

{% block body %}
    <h1>Figurines</h1>
    <div class="container">
        <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ figurine.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ figurine.name }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ figurine.picture }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ figurine.price }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ figurine.slug }}</td>
            </tr>
            <tr>
                <th>ShortDescription</th>
                <td>{{ figurine.shortDescription }}</td>
            </tr>
        </tbody>
        </table>
    </div>
    
    <div class="d-flex">
        <a href="{{ path('figurines_edit', {'id': figurine.id}) }}">edit</a>
        <a href="#">{{ include('figurine/_delete_form.html.twig') }}</a>
    </div>
    
    <a href="{{ path('app_figurines') }}">back to list</a>
{% endblock %}

templates/figurine/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Page de {{ figurine.name }}
{% endblock %}

{% block body %}

    
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{path('homepage')}}">Accueil</a></li>
        <li class="breadcrumb-item">
            <a href="{{path('figurine_category', {'slug': figurine.category.slug})}}">{{figurine.category.categoryName}}</a></li>
        <li class="breadcrumb-item active">{{figurine.name}}</li>
    </ol>
    <h1 class="text-center">{{ figurine.name }}</h1> 
    
    <div class="row">
        <div class="col-4">
            <img class="img-fluid" src="{{figurine.picture}}" alt="img">
        </div>
        <div class="col">
        <span class="badge rounded-pill bg-info">
                {{figurine.category.categoryName}}
            </span>
            <p>{{figurine.shortDescription}}</p>
            <a href="{{ path('cart_add', {'id': figurine.id} ) }}" class="btn btn-success"><i class="fas fa-shopping-cart"></i>
                Ajouer au panier
            </a>
        </div>
    </div>
{% endblock %}